services:
  app:
    image: rupesh898/oidc-server:latest
    container_name: oidc-jenkins
    environment:
      - DEBUG=False
      - MONGODB_URI=mongodb://mongo:27017/oidc
      - PORT=8000
      - OIDC_ISSUER=https://oidc-token.radiantcloud.in
      - PRIVATE_KEY_PATH=keys/private.pem
      - PUBLIC_KEY_PATH=keys/public.pem
      - OIDC_KEY_ID=f3d31c42-53bf-4cd9-8912-74df7be06bb7
      - PROJECT_NUMBER=883614808385
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:7
    container_name: oidc-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data:
