services:
  app:
    image: rupesh898/oidc-jenkins-gcp-wif-app:latest
    command: >
      sh -c "
      python manage.py migrate &&
      python manage.py seed_jenkins &&
      python manage.py runserver 0.0.0.0:8000
      "
    container_name: oidc-jenkins
    env_file:
      - .env
    environment:
      - DEBUG=False
    ports:
      - "8000:8000"
      - "8080:8080"
    restart: unless-stopped
