services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "
      python manage.py migrate &&
      python manage.py seed_jenkins &&
      python manage.py runserver 0.0.0.0:8000
      "
    container_name: oidc-jenkins
    environment:
      - DEBUG=False
      - OIDC_ISSUER=TODO
      - PRIVATE_KEY_PATH=keys/private.pem
      - PUBLIC_KEY_PATH=keys/public.pem
      - SECRET_KEY="django-insecure-w=y(*#)#4^b#g3-9amyl*w1m*$%9pukoy*-#^-2-r1-r+*^u_t"
    ports:
      - "8000:8000"
      - "8080:8080"
    restart: unless-stopped
